### ISSUE TITLE
Switch to Transifex API

### ISSUE THREAD

**Issue by tjvr** [scratchblocks/scratchblocks#214]
<https://translate.scratch.mit.edu> is now deprecated. The Scratch Team have switched to [Transifex](https://www.transifex.com/llk/scratch-legacy/) instead.

We need to update [src/fetch_translations.js](https://github.com/scratchblocks/scratchblocks/blob/90858e8ad846423b40aeacea5db7dfdaad81de1d/src/fetch_translations.js) to use the Transifex API. It looks like there's some  [API documentation](https://docs.transifex.com/api/introduction).

**Comment by chrisgarrity** [comment]
@tjvr Transifex does have an API, but user credentials (e.g. translator login) are needed to use it. However, https://github.com/LLK/scratchr2_translations is a repository that is updated nightly from transifex. scratchr2_translations can be installed as a submodule, or as an npm module (see https://github.com/LLK/scratch-www/blob/develop/package.json for an example install) Then fetch_translations.js just needs to access the local files instead of pulling from the old server.

Also, just a head's up - the old server must be shut down on or before September 1st, 2017.  Please let us know if you don't need it any more.

**Comment by chrisgarrity** [comment]
Just a quick note that we've reduced the scratchr2_translations updates to weekly, nightly was just creating a lot of noise in the dependencies.

**Comment by tjvr** [comment]
Fine by me! Thanks for keeping me updated 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
