### ISSUE TITLE
Are you working on an update for 3.0?

### ISSUE THREAD

**Issue by NitroCipher** [scratchblocks/scratchblocks#239]
Looking at your latest commits, I am wondering if you are working on writing a new version based on Scratch 3.0

(in reference to "move renderer to scratch2 package")

I have a fork that I am working on for 3.0. It is here: [s3blocks.github.io](https://s3blocks.github.io) if you want to take a look

**Comment by tjvr** [comment]
> I have a fork that I am working on for 3.0

Yes, I’m aware :)

I’ve never planned to write a Scratch 3 version of scratchblocks. However, the Code Club / Raspberry Pi Foundation folks would like to see scratchblocks updated, since they use it for project guides.

I’d be sad to see the project forked. I’m very aware that the codebase was a bit of a mess before; so I’ve been trying to tidy things up, and split out the Scratch 2 renderer from the parser, in the hope that someone (such as yourself!) would be able to pick up adding a Scratch 3 renderer to the project.

Would you be interested in merging your changes back into scratchblocks? 😃

**Comment by NitroCipher** [comment]
I'd definitely be interested in merging, I have a few scaling issues at the moment (with input fields) that I'd like to fix before-hand. 
(I've invited you the the s3blocks github organization btw)

**Comment by pdawyndt** [comment]
Here's [another version for Scratch 3.0 blocks](https://scratch4d.github.io/scratch-LN/)

**Comment by NitroCipher** [comment]
@pdawyndt Oh wow! That looks good! The block syntax is different than scratchblocks, but I'm sure it can be tweaked. I haven't had a lot of time recently to actually work on s3blocks, so it has been difficult to keep up. I might just concede and let this take them helm. I hope this thing won't require too much modifications to work on the scatch servers

**Comment by pdawyndt** [comment]
@NitroCipher For your reference, here's a link to the [grammar rules](https://github.com/scratch4d/scratch-LN/blob/develop/documentation_parser/generated_diagrams.png) used by the language.

**Comment by NitroCipher** [comment]
_\*hangs up my hat\*_
I've got to say, I'm impressed.

**Comment by tjvr** [comment]
@NitroCipher Are you referring to Scratch-LN?

I must admit I wasn't aware of Scratch-LN when I started work on scratchblocks! Seems pretty impressive. I always hoped that someone would hook up the existing scratchblocks parser to the Scratch Team's fork of Blockly, which seems to similar to what's done here (albeit with a different parser). I imagine the new Scratch 3.0 renderer in scratchblocks is more lightweight, though! 😊 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NitroCipher** [comment]
@tjvr I am talking about scratchblocks. Sorry for the confusion

**Comment by tjvr** [comment]
I think we've answered this question 😊
