### ISSUE TITLE
"when green flag clicked" image broken in Japanese.

### ISSUE THREAD

**Issue by kiyokura** [scratchblocks/scratchblocks#245]
An incorrect image is generated when generate Japanese translated image of "when green flag clicked" block.
(However, a correct image is generated On "scratchblocks translator".)

Expected image (in "scratchblocks translator"):
![image](https://user-images.githubusercontent.com/558604/40597347-efac2788-627b-11e8-85fb-b2219cb813b7.png)

Actual image:
![image](https://user-images.githubusercontent.com/558604/40597370-19716948-627c-11e8-967f-cb90012914a2.png)

**Comment by tjvr** [comment]
Hey, thanks for the report!

The reason it works on the translator is that I haven't updated the version of scratchblocks that the translator's using, yet.

I was hoping that #238 would fix this, but it looks like it doesn't 🤔  I've added a test for this, so hopefully this should be fixed in the next release. 🙂
