### ISSUE TITLE
Cannot use scratchblocks from Node.js

### ISSUE THREAD

**Issue by exKAZUu** [scratchblocks/scratchblocks#293]
`require('scratchblocks')` causes the following error:

```
ReferenceError: window is not defined
```

**Comment by exKAZUu** [comment]
[jsdom](https://github.com/jsdom/jsdom/) and [node-canvas](https://github.com/Automattic/node-canvas) can fix this issue, but I believe we should fix #294 at first.

**Comment by tjvr** [comment]
Using scratchblocks from node.js is not supported. We used to use node-canvas, but it wasn't ideal, so we removed it. In particular, we care a lot about text metrics, and since those are specific to your installed fonts it doesn't make sense to generate SVGs on the server which may be rendered with different fonts installed.

If you want to render scratchblocks on the server, it's recommended you use headless Chrome or phantom.js etc, and render to PNG. 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by exKAZUu** [comment]
I see, thank you for the explanation!

**Comment by BoomerScratch** [comment]
@tjvr @exKAZUu I have found a hacky fix using jsdom and node-canvas (it will return an non-zero exit code if you don't install canvas):
```javascript
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const window = new JSDOM("<pre class='blocks'>Hello world</pre>");
const scratchblocks = require("scratchblocks/index.js")(window.window);
scratchblocks.renderMatching("pre.blocks",{
  style: "scratch3",
  languages: ["en"]
});
console.log(window.window.document.querySelector("div.scratchblocks").innerHTML);
```
It outputs the SVG code in the console. It is not the best, but it works! :wink: (I tested it in repl.it)
