### ISSUE TITLE
Use alias for latest version on website

### ISSUE THREAD

**Issue by Ascor8522** [scratchblocks/scratchblocks#349]
Publishing new version every now and then makes it hard for everybody to keep their project up to date.
Please consider making a new url on the website as an alias for the latest version.

This can easily be done with GH Pages and Jelkyll (see https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site and https://github.com/jekyll/jekyll-redirect-from)

E.g. `https://scratchblocks.github.io/js/scratchblocks-3.latest-min.js` would redirect to `https://scratchblocks.github.io/js/scratchblocks-v3.5-min.js` (since it's the latest version at the time of writing)

When breaking changes are made for the lib user, the major revision number is changed, but that does not impact the link.

**Comment by ksdavidc** [comment]
I second this. It took me quite a while to figure out that the hardlink I copied from your readme for ver 3.4 was linking to the wrong place, so my code wasn't working. ;-)

**Comment by tjvr** [comment]
Thanks for raising! I've (belatedly) updated the readme to omit any mention of particular versions, so hopefully this particular confusion shouldn't happen again :)

I appreciate the suggestion about aliases but I think it's much better if people have to consciously update: I'd encourage people to _copy_ scratchblocks into their projects, rather than linking directly to the JS file on `scratchblocks.github.io`.

For an example, we recently fixed a bug in how padding worked (#301). That didn't merit a major version on its own, but for some users it could be a breaking change, since they'd used code to work around it that would conflict with the fix!
