### ISSUE TITLE
"say()" block coloring in German

### ISSUE THREAD

**Issue by LiFaytheGoblin** [scratchblocks/scratchblocks#374]
Hi all,
in German, the blocks say() from the speech extension and the block say() from looks are called the same. So when I mean to use the looks block (almost all the time) it renders it as the speech extension block. It should per default render it as the looks block tho, since that is the usual case.
![image](https://user-images.githubusercontent.com/5471273/125397451-410b3400-e3ae-11eb-8769-0770428e76c1.png)

**Comment by apple502j** [comment]
@tjvr In this case it's impossible to disambiguate the two since argument types and names are the same. Just like how we can't separate Makey Makey "when key pressed" and normal "when key pressed" in English.

Note that this is the opposite of #369 - in this case, two differently-named blocks that do not have the disambiguation share the same name in other languages, and in #369 two blocks sharing the name in English does not share names in other languages.

**Comment by apple502j** [comment]
That said @tjvr we can add a disambiguation code that always makes the say block looks block (should be easy)

**Comment by apple502j** [comment]
Hmm @tjvr Turns out this isn't easy either; if I add disambiguation rule it applies to other languages as well.

We should re-write the whole code IMO. The current code is based on wrong assumption - if one language needs disambiguation, all do. The very first thing to do would be to switch from objects to multidict-like representation that can handle two values with the same key.

**Comment by apple502j** [comment]
@tjvr What do you think is the best solution?

Current problems:
1) Disambiguation applies to all languages, even if that's unnecessary for a particular language
2) We use block's scratchblocks notation (e.g. `say %1`) in various keys of objects/maps, which does not work well with duplicates (e.g. `Sage %1` for looks_say is overwritten by `Sage %1` for TTS because keys must be unique). We should either use keys that are guaranteed to be unique (e.g. block opcode, `looks_say`) or convert to array, though both will result in O(n) lookup instead of O(1).

**Comment by apple502j** [comment]
@tjvr That could work, I guess
