### ISSUE TITLE
Extra whitespace after generated SVGs

### ISSUE THREAD

**Issue by BirdLogics** [scratchblocks/scratchblocks#431]
For some reason, SVG exports have extra whitespace at the bottom of the canvas. For a visualization of what's going on, see [the GitHub preview](https://github.com/BirdLogics/sb3topy/blob/master/docs/scratchblocks/svg/motion.svg) of an exported SVG. The preview shows how the SVG canvas extends past the actual content.

You can also see the extra white space on the [scratchblocks website](https://scratchblocks.github.io/#?style=scratch3&script=move%20(10)%20steps%0A%0Aturn%20cw%20(15)%20degrees%0A%0Aturn%20ccw%20(15)%20degrees%0A%0Ago%20to%20(random%20position%20v)%0A%0Aglide%20(1)%20secs%20to%20(random%20position%20v)%0A%0Aglide%20(1)%20secs%20to%20x%3A%20(0)%20y%3A%20(0)%0A%0Apoint%20in%20direction%20(90)%0A%0Apoint%20towards%20(mouse-pointer%20v)%0A%0Achange%20x%20by%20(10)%0A%0Aset%20x%20to%20(0)%0A%0Achange%20y%20by%20(10)%0A%0Aset%20y%20to%20(0)%0A%0Aset%20rotation%20style%20%5Bleft-right%20v%5D%0A%0A(x%20position)%0A%0A(y%20position)%0A%0A(direction)). Notice how you can continue scrolling down past the blocks. The extra scrolling space is caused by the extra space at the end of the image.

<img src="https://user-images.githubusercontent.com/47367734/166129512-168f6cba-dd28-4714-b900-88b2f9a15c87.png" width="50%">

Although the extra space may not seem like a huge deal, it looks ugly when text or other content is placed immediately after the SVG image. For example, see [this doc](https://github.com/BirdLogics/sb3topy/blob/master/docs/supported_blocks.md) which I was writing when I discovered the issue.

<img src="https://user-images.githubusercontent.com/47367734/166129624-5f443161-822e-4f12-96d9-e34163195854.png" width="50%">

**Comment by apple502j** [comment]
transform in the SVG should be applied to the parent element instead. Hopefully this does not screw up existing stuff (we have control over the styles of renderMatching-ed elements right?)

**Comment by tjvr** [comment]
> we have control over the styles of renderMatching-ed elements right?

We apply styles to the SVG using CSS, if that's what you mean?

**Comment by apple502j** [comment]
@tjvr Current DOM structure:

```html
<pre class="blocks"><svg style="...">
```

Fix:

```html
<pre class="blocks" style="..."><svg>
```

The problem is that if other scripts do things like `block.style =` it breaks. So the question is whether it counts as a breaking change to modify the styles of the element itself, not their children.

**Comment by tjvr** [comment]
@apple502j Looking into this I'm not sure I agree that we need to apply styles to the SVG's parent.

The issue appears to be that we set a width/height on the SVG -- eg `width="1000" height="2000"` -- but also a `style="transform: scale(0.675)`. This is used for Scratch 3 in particular, to match the default zoom in the editor, while still laying out the blocks using the same dimensions as they use. The result is that the SVG only takes up 675px by 1350px.

I think a better solution would be to wrap the SVG's entire contents in a group `<g>` and apply the scale transform to that? Then we can apply the scale to the SVG's dimensions, so that its size matches the actual size it will be displayed.

Either way, this should strictly be a semver change; not many people actually follow semver that strictly though, as far as I can tell :P
