### ISSUE TITLE
Support new block colors (June 2023 Scratch update)

### ISSUE THREAD

**Issue by icomputeUK** [scratchblocks/scratchblocks#458]
Do you have plans/timescales for adapting scratchblocks to match Scratch's new high color contrast blocks?

As planned here: https://lab.scratch.mit.edu/contrast-blocks/

**Comment by tjvr** [comment]
This is the first I've heard of them. Thanks for the link!

If people would find this useful, do let me know.

**Comment by apple502j** [comment]
@tjvr This needs to be done urgently; we only have six weeks or so before this drops in an official update, according to sources (for those who can access it, see Transifex announcement). Scratch Wiki and other programs would need the updated block.

I will try to address the stuff this weekend. The new colors would be a separate theme, since the old colors would still be useful.

**Comment by tjvr** [comment]
@apple502j Thank you for looking into this!

> The new colors would be a separate theme, since the old colors would still be useful.

I agree with putting the old colours behind an option (with the new ones as the default). But we want to reuse almost all of the existing renderer. Can you share how you're planning to update the implementation and the public interface?

**Comment by apple502j** [comment]
@tjvr Right now colors are both hardcoded in the JS and in the CSS file. It might be a wise idea to use CSS variables, which is (surprisingly) added before Fetch API on Firefox and Safari, and is supported by all browsers that Scratch supports. I believe the current output already breaks on, say, Inkscape, so that shouldn't be a big deal.

**Comment by tjvr** [comment]
What advantage does CSS variables give us?

I can see the sense in making more use of classes so the CSS controls all the colors. But would it not work to just swap out what stylesheet we're using?

That said: if you feel strongly about it it seems wrong of me to stop you!

**Comment by apple502j** [comment]
@tjvr The most obvious answer is that it allows custom color definitions, such as colors used in Scratch Addons theme. It is also easier to update in case Scratch changes it again, because each color is defined only once. This also reduces bugs like #472. Plus, there would be less CSS code duplication with this.

**Comment by tjvr** [comment]
> less CSS code duplication

This is just because we have to define separate classes for `fill` and `stroke`? That level of duplication doesn't really strike me as a concern.

As it happens our current SVGs _mostly_ work in e.g. Inkscape, it's just the icons that don't seem to work (presumably since they use `<def>`). It might be nice to keep support for that--I've occasionally heard of people getting SVGs from scratchblocks and then manually editing them in a vector graphics program like Inkscape--but it's probably not the end of the world to break this further.

Interestingly I don't think we've ever attempted to define what browsers we support. The main use case for scratchblocks is probably educational content around Scratch (the wiki, forums, Code Club projects, etc), so supporting at least the browsers that Scratch do, like you suggested, makes sense to me.

I wonder if we need to support older browsers as well? You might have downloaded a copy of Scratch, or want to read materials on an older device. I think the [Raspberry Pi Foundation](https://projects.raspberrypi.org/en/codeclub) are one of the largest users of scratchblocks, but I'm not sure how to find out what browsers they support. And I suppose most browsers are automatically kept up-to-date now anyway; and iOS has had support for this specific feature since iOS 9 in 2015, which seems pretty old. What do you think?

Also: how are you thinking we'll specify the new theme in the options?

**Comment by apple502j** [comment]
I have changed it so that the styles are now prefix-matched (e.g. `scratch3-new`). The svg would also have an additional class to supply the CSS var definition.

CSS variable is supported in Chrome 49 (March 2016) and Firefox 31 (July 2014). The most obvious answer for "what would we break?" is Internet Explorer, but that browser is dead. It is likely that some managed devices that have fixed software versions and is somehow not hit by all those zero-days would have such an outdated software, but I do not have information on this.

**Comment by tjvr** [comment]
Yeah, if all we're breaking is IE, that sounds fine to me! 😅

**Comment by icomputeUK** [comment]
Thank you for your work on this. Could you let me know where I can access the changes?

https://scratchblocks.github.io/ doesn't have the new colour options.

**Comment by tjvr** [comment]
@icomputeUK This is now available, if you haven't seen by now!
