### ISSUE TITLE
I keep having this problem with the Scratch 2 style and it's really bugging me

### ISSUE THREAD

**Issue by memesong** [scratchblocks/scratchblocks#460]
I don't know if this is just my device this happens with, but the Scratch 2 style seems to not work a lot of the time. I have video reference of the program being unresponsive here

https://user-images.githubusercontent.com/73676670/203679140-1ea94363-9522-430f-805b-84390e4944ca.mp4

and as you can see in the recording, after I type in the "ring" shape that I want the block to take, nothing seems to work anymore. I tested afterwards by taking out the "ring" keyword, and apparently, that's what prevents it from doing anything. The ring shape just makes the entire block not work. This works just fine in the Scratch 3 style; it's just 2.0 that's the problem.

**Comment by tjvr** [comment]
Do you see anything in the JS console?

Can you post a minimal example here? (i.e. the shortest possible code that triggers the bug)

**Comment by memesong** [comment]
I think the way this happens is that I just go into the Scratch 2.0 style and type in anything with a ring shape, and everything on and below that line ceases to function. For example:
`run ((\ ::control stack) ::grey ring) //Doesn't show up as ring`
I just tested it again, and instead of ceasing to function, it just worked inconsistently. When I changed the shape of the ring block like this:
`((\ ::control stack) ::grey ring cap)`
it just changed the ring to a cap block. Then I deleted the keyword "cap," and the block wouldn't update until I deleted the last letter of "ring." Here's another video for reference:

https://user-images.githubusercontent.com/73676670/204066905-c4c67901-9c66-40c7-84f6-02a8cf4b0d55.mp4

As you can see at the end, the block doesn't update back to the "ring" block type until I delete the letter "p" from cap, as previously stated. It doesn't even let me type a comment on that line!

**Comment by tjvr** [comment]
> Are you talking about the dev tools menu/Inspect Element?

Yes! In the dev tools there should be a "Console" tab. Do you see any errors in there?

**Comment by memesong** [comment]
I don't know what exactly is wrong here, but I think you could maybe interpret what was wrong from this additional video:

https://user-images.githubusercontent.com/73676670/205410012-199a7335-7f99-4160-8a69-7c26cc6b92f1.mp4

**Comment by tjvr** [comment]
Thanks for sharing! Okay, so that confirms there's definitely an error here: an assertion in the code is failing.

And just like you said, we can clearly see that the error appeared as soon as you finished typing "ring":
```
run ((::control) ::grey ring
```
We don't appear to have working source maps in the production build (unfortunately!), but using this input I can reproduce this locally. That shows me that this line is the culprit:
<https://github.com/scratchblocks/scratchblocks/blob/17b5a5d13753a93aa11582ab8ffe0a00cf27a070/scratch2/draw.js#L113>
It may take some time to figure out what this code is doing, given it dates from over six years ago :sweat_smile:

**Comment by tjvr** [comment]
I think I found it!
