### ISSUE TITLE
You forgot 2 block layouts

### ISSUE THREAD

**Issue by RememberG2** [scratchblocks/scratchblocks#495]
Scratch 1.4 and Scratch 0.1 block layout is required.

- [ ] add 1.4 block layout
- [ ] add 0.1 block layout

**Comment by CST1229** [comment]
Not required, I'm pretty sure the 2.0 blocks are only there as kind of a legacy leftover from back when this library rendered 2.0 blocks only.

**Comment by RememberG2** [comment]
On Thursday, August 31, 2023, CST1229 ***@***.***> wrote:
> Not required, I'm pretty sure the 2.0 blocks are only there as kind of a
legacy leftover from back when this library rendered 2.0 blocks only.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/m63mPdpLxiRnNFDOhqlW7-iC9ZrMysD8kpktHJCLVz_c5AeKf9Dywa6JjQrp0yRqYdQt0VdAs2u1GSw1eG3y3bQSEoadWtLWg1sUmhSairaraQOm6cdSJS-7GRHtdiRG1gFzMB2xRbPGflmCtSWuuhAE9G_IAISYYjuNsyphl2om4LGZggv9OkEznLZI6dF7TA5tzMn9zbjzSq1lMWvAuT3n0oWYu8ielTCTqfaz4yDgQnL9jw=s0-d-e1-ft#https://github.com/notifications/beacon/BCIVEDZHJ2U5CV64UXH4M2LXYDJOLA5CNFSM6AAAAAA4GNPIHGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTFNOWBM.gif>Message
ID: ***@***.***>
But Its impossible to make 1.4 blocks such as "forever if <>"

**Comment by tjvr** [comment]
It is unlikely that anyone will do the work to add Scratch 1.4 blocks. The library is primarily intended for educational content, including wikis, and it is unlikely anyone is still using Scratch 1.4 for teaching.

The Scratch 2.0 theme is not accidental however, when Scratch 3.0 was released I deliberately added theming support so that the one library can support both themes, since this is useful for some users.

You can write "forever if" using the `:: control` modifier: [example](http://scratchblocks.github.io/#?style=scratch3&script=forever%20if%20%3C%3E%20%3A%3A%20control).
